name: fft
description: A library for fourier transformations using the Cooley-Tukey algorithm
version: 0.0.15
author: Edouard Tavinor <edouardtavinor@gmail.com>
homepage: https://github.com/ehrt74/dart_lang_fft

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  my_complex: ">=0.0.1 <0.1.0"
  tuple: ">=1.0.1 <2.0.0"

dev_dependencies:
  test: '>=0.12.0 <2.0.0'